//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int idCurso { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> descripcion { get; set; }
    }
}
